### ISSUE TITLE
[feature] add a dark-mode toggle

### ISSUE THREAD

**Issue by mrossinek** [mitmproxy/pdoc#800]
#### Problem Description

Light- vs. dark-mode toggles have become pervasive across websites. Even though this can be considered a fairly niche problem, tackling this for pdoc-generated docs has intrigued me. I am aware that a dark mode example exists, but currently the developer has to choose which theme to use at compile time.

#### Proposal

A light/dark theme toggle would be a great yet simple-to-achieve feature for pdoc. Especially since the introduction of the [`light-dark()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) CSS function from 2024, which has found [good adoption](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark#browser_compatibility) already. Leveraging this, I was able to hack a theme toggle into my pdoc-generated docs with minimal changes:

| system-default | light | dark |
|-|-|-|
| ![Image](https://github.com/user-attachments/assets/b23924b3-bf00-48b7-b2d2-a6f88ad79128) | ![Image](https://github.com/user-attachments/assets/f84d1be7-741f-4e07-965c-4fa69747274f) | ![Image](https://github.com/user-attachments/assets/d2640893-e672-4e40-8b61-7ace82c38a41) |

#### Alternatives

Without the use of `light-dark()` CSS function, a solution is likely possible, but exceeds my knowledge of HTML, CSS, and Javascript even more than this hack does 😅 

#### Additional context

Here are the two changes I had to do to implement the above. I am happy to upstream these, if this feature gets considered:

<details>
<summary>Combine the default <code>theme.css</code> with the dark-mode colors into a single file using the <code>light-dark()</code> CSS function.</summary>

```css
:root {
    color-scheme: light dark;

    --pdoc-background: light-dark(#fff, #212529);
}

.pdoc {
    --text: light-dark(#212529, #f7f7f7);
    --muted: light-dark(#6c757d, #9d9d9d);
    --link: light-dark(#3660a5, #58a6ff);
    --link-hover: light-dark(#1659c5, #3989ff);
    --code: light-dark(#f8f8f8, #333);
    --active: light-dark(#fff598, #555);

    --accent: light-dark(#eee, #343434);
    --accent2: light-dark(#c1c1c1, #555);

    --nav-hover: light-dark(rgba(255, 255, 255, 0.5), rgba(0, 0, 0, 0.1));
    --name: light-dark(#0066BB, #77C1FF);
    --def: light-dark(#008800, #0cdd0c);
    --annotation: light-dark(#007020, #00c037);
}
```
</details>

<details>
<summary>Hack the toggle button into the <code>module_list_link</code> jinja block inside of the <code>module.html.jinja2</code> template.</summary>

```diff
diff --git a/pdoc/templates/default/module.html.jinja2 b/pdoc/templates/default/module.html.jinja2
index 555ebdc..dcadc88 100644
--- a/pdoc/templates/default/module.html.jinja2
+++ b/pdoc/templates/default/module.html.jinja2
@@ -16,6 +16,33 @@
                 Module Index
             </a>
         {% endif %}
+        <button class="pdoc-button module-list-button" id="cycleTheme" onclick="cycleMode()">
+            <i class="fa-solid fa-circle-half-stroke"></i>
+        </button>
+        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css'>
+        <script>
+        const html = document.querySelector('html');
+        html.style.setProperty('color-scheme', 'light dark');
+        function cycleMode() {
+          mode = html.style.getPropertyValue('color-scheme');
+          switch (mode) {
+              case 'light dark':
+                  mode = 'light';
+                  text = '<i class ="fa-solid fa-sun"></i>';
+                  break;
+              case 'light':
+                  mode = 'dark';
+                  text = '<i class ="fa-solid fa-moon"></i>';
+                  break;
+              case 'dark':
+                  mode = 'light dark';
+                  text = '<i class ="fa-solid fa-circle-half-stroke"></i>';
+                  break;
+          }
+          html.style.setProperty('color-scheme', mode);
+          document.querySelector('#cycleTheme').innerHTML = text;
+        }
+        </script>
     {% endblock %}
 
     {% block nav_title %}
```

This hack can be done inside of a custom `module.html.jinja2` template by overwriting the entire `module_list_link` block, but to emphasize the minimal code change required inside of pdoc I chose to show the git diff directly here.
</details>

This is obviously a hack and I assume that there are more elegant solutions for the Javascript, but it works as a proof of concept. I was fiddling around with the alignment of the button (which is still not perfect) by setting some additional CSS variables for the `#cycleTheme` id and `.fa-solid` classes, but those are details that can be figured out later.

And obviously one can find better icons than I used here.
